spring:
  application:
    name: Merchants
  datasource:
    url: jdbc:mysql://localhost:3306/passbook?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone =Asia/Shanghai
    username: root
    password: 415669945tjw
    driver-class-name: com.mysql.jdbc.Driver
    name: passbook
    type: com.alibaba.druid.pool.DruidDataSource
  kafka:
    bootstrap-servers: 127.0.0.1:9092
    consumer:
      group-id: passbook
    listener:
      concurrency: 4
  mybatis:
    mapper-location: classpath:/resources/mapping/*.xml
server:
  port: 9527
logging:
  level:
    com.project.passbook: debug
  file:
    name: ./merchants.log
