package com.project.passbook.dao;

import com.project.passbook.DataObject.MerchantsDo;
import com.project.passbook.DataObject.MerchantsDoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;

@Repository
public interface MerchantsDoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    long countByExample(MerchantsDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    int deleteByExample(MerchantsDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    int insert(MerchantsDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    int insertSelective(MerchantsDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    List<MerchantsDo> selectByExample(MerchantsDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    MerchantsDo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    int updateByExampleSelective(@Param("record") MerchantsDo record, @Param("example") MerchantsDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    int updateByExample(@Param("record") MerchantsDo record, @Param("example") MerchantsDoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    int updateByPrimaryKeySelective(MerchantsDo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table merchants
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    int updateByPrimaryKey(MerchantsDo record);
}