package com.project.passbook.DataObject;

public class MerchantsDo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants.id
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants.name
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants.logo_url
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    private String logoUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants.business_license_url
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    private String businessLicenseUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants.phone
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants.address
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column merchants.is_audit
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    private Boolean isAudit;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants.id
     *
     * @return the value of merchants.id
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants.id
     *
     * @param id the value for merchants.id
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants.name
     *
     * @return the value of merchants.name
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants.name
     *
     * @param name the value for merchants.name
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants.logo_url
     *
     * @return the value of merchants.logo_url
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    public String getLogoUrl() {
        return logoUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants.logo_url
     *
     * @param logoUrl the value for merchants.logo_url
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    public void setLogoUrl(String logoUrl) {
        this.logoUrl = logoUrl == null ? null : logoUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants.business_license_url
     *
     * @return the value of merchants.business_license_url
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    public String getBusinessLicenseUrl() {
        return businessLicenseUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants.business_license_url
     *
     * @param businessLicenseUrl the value for merchants.business_license_url
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    public void setBusinessLicenseUrl(String businessLicenseUrl) {
        this.businessLicenseUrl = businessLicenseUrl == null ? null : businessLicenseUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants.phone
     *
     * @return the value of merchants.phone
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants.phone
     *
     * @param phone the value for merchants.phone
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants.address
     *
     * @return the value of merchants.address
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants.address
     *
     * @param address the value for merchants.address
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column merchants.is_audit
     *
     * @return the value of merchants.is_audit
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    public Boolean getIsAudit() {
        return isAudit;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column merchants.is_audit
     *
     * @param isAudit the value for merchants.is_audit
     *
     * @mbg.generated Tue Jun 22 00:00:06 CST 2021
     */
    public void setIsAudit(Boolean isAudit) {
        this.isAudit = isAudit;
    }
}